baseURL = 'https://askerychai.github.io/12-microstartups/'
publishDir = 'docs'
languageCode = 'ru'
title = '12 microstartups'
theme = 'hextra-main'

[params]
  description = "12 microstartups - блог о микростартапах"
  
  [params.footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = true