baseURL = 'https://ch12ms.online/'
publishDir = 'docs'
languageCode = 'ru'
title = '12 microstartups'
theme = 'hextra-main'

[params]
  description = "12 microstartups - блог о микростартапах"
  
  [params.navbar]
    displayTitle = true
    displayLogo = true
    [params.navbar.logo]
      path = "images/logo.svg"
      dark = "images/logo.svg"
      width = 40
      height = 20
      link = "/"
  
  [params.footer]
    enable = true
    displayCopyright = false
    displayPoweredBy = false
  
  [params.theme]
    default = "dark"
    displayToggle = true
  
  [params.blog.list]
    displayTags = true
    sortBy = "date"
    sortOrder = "desc"
    pagerSize = 20

  [params.blog.article]
    displayPagination = true

enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[[menu.main]]
  name = "Стать участником"
  pageRef = "/podpiska"
  weight = 1

[[menu.main]]
  identifier = "blog"
  name = "Блог"
  pageRef = "/posts"
  weight = 2

[[menu.main]]
  identifier = "baza-znaniy"
  name = "База знаний"
  weight = 3

[[menu.main]]
  identifier = "koncepciya"
  name = "Концепция проекта"
  pageRef = "/pages/koncepciya-chelenja"
  parent = "baza-znaniy"
  weight = 1

[[menu.main]]
  identifier = "pravila"
  name = "Правила участия"
  pageRef = "/pages/pravila-uchastiya"
  parent = "baza-znaniy"
  weight = 2

[[menu.main]]
  identifier = "chto-takoye"
  name = "Что такое микростартап"
  pageRef = "/pages/chto-takoye-microstartup"
  parent = "baza-znaniy"
  weight = 3

[[menu.main]]
  identifier = "kak-zapuskat"
  name = "Как запускать микростартап"
  pageRef = "/pages/process-zapuska-microstartupa"
  parent = "baza-znaniy"
  weight = 4

[[menu.main]]
  identifier = "validaciya"
  name = "Валидация идеи"
  pageRef = "/pages/idea-validation-checklist"
  parent = "baza-znaniy"
  weight = 5

[[menu.main]]
  identifier = "shablon-intervyu"
  name = "Шаблон интервью"
  pageRef = "/pages/shablon-intervyu-s-clientom"
  parent = "baza-znaniy"
  weight = 6

[[menu.main]]
  identifier = "kanban"
  name = "Канбан доска"
  pageRef = "/pages/kanban"
  parent = "baza-znaniy"
  weight = 7